INSERT INTO categories VALUES(0, 'food');
INSERT INTO categories VALUES(1, 'daily necessities');
INSERT INTO categories VALUES(2, 'rent');
INSERT INTO categories VALUES(3, 'water');
INSERT INTO categories VALUES(4, 'gas');
INSERT INTO categories VALUES(5, 'electricity');
INSERT INTO categories VALUES(6, 'gasoline');
INSERT INTO categories VALUES(7, 'leisure');
INSERT INTO categories VALUES(8, 'saving');
INSERT INTO categories VALUES(9, 'others');